//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponManagementServiceV2.Core.Model.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CouponManagementServiceV2.Core.Model.Shared.Resources.ErrorCode", typeof(ErrorCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -14.
        /// </summary>
        public static string BLOCK_COUPON {
            get {
                return ResourceManager.GetString("BLOCK_COUPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -10.
        /// </summary>
        public static string DATE_EXPIRED {
            get {
                return ResourceManager.GetString("DATE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -9.
        /// </summary>
        public static string DRAFT_COUPON {
            get {
                return ResourceManager.GetString("DRAFT_COUPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -3.
        /// </summary>
        public static string INVALID_LOGIN {
            get {
                return ResourceManager.GetString("INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -11.
        /// </summary>
        public static string NO_ACTIVATE {
            get {
                return ResourceManager.GetString("NO_ACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -15.
        /// </summary>
        public static string NO_BLOCK {
            get {
                return ResourceManager.GetString("NO_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -18.
        /// </summary>
        public static string NO_COUPON {
            get {
                return ResourceManager.GetString("NO_COUPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -4.
        /// </summary>
        public static string NO_COUPON_ID {
            get {
                return ResourceManager.GetString("NO_COUPON_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -5.
        /// </summary>
        public static string NO_COUPON_SERIE {
            get {
                return ResourceManager.GetString("NO_COUPON_SERIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -6.
        /// </summary>
        public static string NO_COUPON_USERNAME {
            get {
                return ResourceManager.GetString("NO_COUPON_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -17.
        /// </summary>
        public static string NO_COUPON_VALID {
            get {
                return ResourceManager.GetString("NO_COUPON_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -13.
        /// </summary>
        public static string NO_DRAFT {
            get {
                return ResourceManager.GetString("NO_DRAFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -7.
        /// </summary>
        public static string NO_LIMIT {
            get {
                return ResourceManager.GetString("NO_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -20.
        /// </summary>
        public static string NO_SERIE {
            get {
                return ResourceManager.GetString("NO_SERIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -12.
        /// </summary>
        public static string NO_USED {
            get {
                return ResourceManager.GetString("NO_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -19.
        /// </summary>
        public static string NO_USER {
            get {
                return ResourceManager.GetString("NO_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -16.
        /// </summary>
        public static string NO_USER_ACTIVITY {
            get {
                return ResourceManager.GetString("NO_USER_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        public static string PROCESS_FAIL {
            get {
                return ResourceManager.GetString("PROCESS_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -8.
        /// </summary>
        public static string USED_COUPON {
            get {
                return ResourceManager.GetString("USED_COUPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -2.
        /// </summary>
        public static string USER_EXIST {
            get {
                return ResourceManager.GetString("USER_EXIST", resourceCulture);
            }
        }
    }
}
